Registered student role
KTH/lms-course-rooms-batch pull request #17
Opened 2022-02-21 14:30 UTC by me97esn

This PR uses another Student role. Note: this PR should be merged and deployed together with a corresponding PR in `lms-sync-users`

2022-03-16 14:17 UTC, jhsware requested changes
It would be nice with a comment on the const values that are declared, see code comment.

2022-03-16 14:17 UTC, jhsware commented on src/lib/enrollmentsUtils.ts
> +const ORIGINAL_STUDENT = 3;
Would be great with a comment on how these constants are determined, perhaps a link somewhere useful.

2022-03-16 14:17 UTC, jhsware commented on src/lib/enrollmentsUtils.ts
> +      },
Thumbs up for adding useful comments!

2022-06-14 08:16 UTC, exacs requested changes

2022-06-14 08:16 UTC, exacs commented on src/lib/enrollmentsUtils.ts
> +      },
Do not handle manually added students. They should be handled manually

2022-06-14 12:00 UTC, me97esn commented
This PR is replaced by this instead: https://github.com/KTH/lms-course-rooms-batch/pull/20

2022-06-14 12:00 UTC, closed without merging