Replace "PERIOD" env. var. to "CURRENT_PERIOD"
KTH/lms-course-rooms-batch pull request #8
Opened 2021-07-02 09:24 UTC by exacs

This PR replaces the environmental variable "PERIOD" with "CURRENT_PERIOD":

- It changes the meaning from "first period when we add antagna" (old "PERIOD" variable) to "current ongoing leanring period" (new "CURRENT_PERIOD" variable)
- To avoid misconfiguration, I have chosen to **replace** the variable instead of reusing the old one.
- It also renews the logic of the app to be adapted to this new variable.
- And replaced the tests. Now, instead of testing the `Period.range` function with some arbitrary values, we test it with something _very close to what the real app does_.

2021-07-07 12:09 UTC, me97esn commented on src/app.js
> +  // which is from "currentPeriod - offset + 1" to "currentPeriod"
Instead of repeating the logic in this comment, can you provide an example? For instance `If current period is X and max offset is Y, previous periods are Z`

2021-07-07 12:18 UTC, me97esn commented on src/lib/period.test.js
> +  expect(Period.range(current, -4, 0).map((c) => c.toString())).toStrictEqual(
When reviewing this PR I realize that I have some problems understanding what this function `Period.range` is supposed to do. What is `startOffset` and `endOffset`? This example above, `Period.range(current, -4, 0)`, what do the numbers -4 and 0 mean? Is it possible to name them or comment to make it more obvious?

2021-07-08 13:16 UTC, me97esn commented on src/app.js
> +  const previousPeriods = Period.range(currentPeriod, -4, 0);
If I configure `CURRENT_PERIOD=2021-VT-P4`, previousPeriods in this line is `2020-HT-P0,2020-HT-P1,2020-HT-P2,2021-VT-P3,2021-VT-P4`. It is a bit confusing that _current_ period is a _previous_ period. I suggest we change the name of this variable to better describe it:
`const currentAndPreviousPeriods = Period.range(currentPeriod, -4, 0);`
Do you object @exacs ?

2021-07-08 13:25 UTC, exacs commented on src/app.js
> +  const previousPeriods = Period.range(currentPeriod, -4, 0);
I am not a big fan of long named variables, specially when they are used only _once_. What would happen if we just replace the variable with its value like this and we get rid of the whole variable?

```diff
-   for (const period of previousPeriods) {
+   for (const period of Period.range(currentPeriod, -4, 0)) {
```

2021-07-08 14:00 UTC, me97esn commented on src/app.js
> +  const previousPeriods = Period.range(currentPeriod, -4, 0);
Yes, _much_ better!

2021-07-16 10:25 UTC, me97esn requested changes
When testing this, I noticed that the app removes antagna from current period. That isn't correct, is it?
I set .env like this: `CURRENT_PERIOD=2021-VT-P4`
Then I noticed this line in the logs: `Handling 2021-VT-P4, removing admitted`.
In this case we should remove antagna up until 2021-VT-P3 but not the current period, if I'm not mistaken.

2021-07-16 10:43 UTC, exacs commented
@me97esn You are mistaken. Before this PR it happened what you say but this PR is about changing that behavior.

Current period is 2021-VT-P4 which means we don't want the antagna students in Canvas.

2021-07-16 20:13 UTC, merged